export enum AuthFormActionKind {
  UPDATE_USERNAME = "UPDATE_USERNAME",
  UPDATE_PASSWORD = "UPDATE_PASSWORD",
  VALIDATE_FORM = "VALIDATE_FORM",
  SET_SERVER_ERROR = "SET_SERVER_ERROR",
  RESET_FORM = "RESET_FORM",
}
