export enum WatchFormActionKind {
  UPDATE_NAME = "UPDATE_NAME",
  UPDATE_BRAND = "UPDATE_BRAND",
  UPDATE_REFERENCE = "UPDATE_REFERENCE",
  VALIDATE_FORM = "VALIDATE_FORM",
  SET_SERVER_ERROR = "SET_SERVER_ERROR",
  RESET_FORM = "RESET_FORM",
}
